#!/usr/bin/env python
from sys import argv
import requests
import os

status = 0

def print_usage():
    print('Usage: ./gitbuildcheck user/repo --shame or ./gitbuildcheck --shame user/repo')
    exit(1)

if len(argv) == 3 and '--shame' in argv:
    if argv[1] == '--shame':
        repo = argv[2]
    else:
        repo = argv[1]
elif len(argv) == 2:
    repo = argv[1]
else:
    print_usage()

url = 'https://github.com/' + repo + '/actions/workflows/python-app.yml/badge.svg'

r = requests.get(url)

if r.status_code == 404:
    print('That is not a repository with pytests.')
    print_usage()
    exit(1)

if 'failing' in r.text:
    status = 1

if '--shame' in argv:
    if status == 1:
        os.system('bash runsiren.sh')


